<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OpenAvP2.Gameplay</RootNamespace>
    <AssemblyName>OpenAvP2.Game</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenAvP2\OpenAvP2.Core.csproj" />
    <ProjectReference Include="..\LithTech\World\OpenAvP2.LithTech.World.csproj" />
    <ProjectReference Include="..\LithTech\Entities\OpenAvP2.LithTech.Entities.csproj" />
  </ItemGroup>
</Project>
