<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Company>OpenAvP2</Company>
    <Authors>Peter Kelly and the OpenAvP2 contributors</Authors>
    <Copyright>Copyright (C) 2026 Peter Kelly and the OpenAvP2 contributors</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Product>OpenAvP2</Product>
    <Version>0.0.1</Version>
  </PropertyGroup>
</Project>
