<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OpenAvP2.Tools.Abc</RootNamespace>
    <AssemblyName>abcdump</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LithTech\Abc\OpenAvP2.LithTech.Abc.csproj" />
  </ItemGroup>
</Project>
