<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OpenAvP2.Tools.Dat</RootNamespace>
    <AssemblyName>datdump</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LithTech$lib\OpenAvP2.LithTech.Dat.csproj" />
  </ItemGroup>
</Project>
